### ISSUE TITLE
Status code 500 error for running over HTTP

### ISSUE THREAD

**Issue by sarnobat** [aws-samples/aws-dynamodb-examples#3]
Exception in thread "main" com.amazonaws.AmazonServiceException: The request processing has failed because of an unknown error, exception or failure. (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: InternalFailure; Request ID: 173ec819-fe6c-4113-9cc6-0cdf1afb8cf7)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1776)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.listTables(AmazonDynamoDBClient.java:1203)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.listTables(AmazonDynamoDBClient.java:1216)
    at com.amazonaws.services.dynamodbv2.DynamoDBLocalFixture1.main(DynamoDBLocalFixture1.java:60)

**Comment by sayrer** [comment]
I'm seeing this too. Is there any way to debug further?

**Comment by buremba** [comment]
The project seems to be abandoned.

**Comment by darrenhaken** [comment]
Is it confirmed that this project is abandoned?

**Comment by cancerian0684** [comment]
This is probably due to Java Library Path issue, for me it started working after I added the below System Property in my IDE

    -Djava.library.path=C:\Setups\sqlite4java-392

I had to download and extract the sqlite4java from this location - https://bitbucket.org/almworks/sqlite4java

I believe this can be set programmatically in the build system too. It would have been much better if Amazon DynamoDB had given more appropriate error.

**Comment by amcp** [comment]
@cancerian0684 I will test the build on Windows and report back here.

**Comment by depend** [comment]
we are seeing the same issue on Mac. Setting java.library.path solved it for now.
